name: Secret Scanning with TruffleHog
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified

    - name: scan-push
      uses: trufflesecurity/trufflehog@main
      with:
          base: ""
          head: ${{ github.ref_name }}

    - name: Run TruffleHog and Save Report
      run: |
        trufflehog --json --only-verified . > trufflehog-report.json
      continue-on-error: true

    - name: Upload TruffleHog Report
      uses: actions/upload-artifact@v2
      with:
        name: trufflehog-report
        path: trufflehog-report.json
