name: Secret Scanning with TruffleHog

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install TruffleHog
      run: |
        python -m pip install --upgrade pip
        pip install trufflehog

    - name: Run TruffleHog Secret Scanning
      id: trufflehog
      run: |
        trufflehog --json --no-git --exclude_path .git --exclude_path .github --exclude_path .vscode . > trufflehog-report.json
        echo "::set-output name=report_path::trufflehog-report.json"

    - name: Upload TruffleHog Report
      uses: actions/upload-artifact@v2
      with:
        name: trufflehog-report
        path: ${{ steps.trufflehog.outputs.report_path }}
